Repository Alom-codingTest/alom-codingTest-25-1, pull requests merged in 2025-05, with the labels that each got.

#75 상급반 / 이혜빈 / 색종이 만들기-2630, 222 풀링-17829, Z-1074, 별 찍기 10-2447
  week5/divide_and_conquer/222_풀링/Hyeblee.java
  week5/divide_and_conquer/5주차_풀이설명_이혜빈.txt
  week5/divide_and_conquer/Z/Hyeblee.java
  week5/divide_and_conquer/별_찍기_10/Hyeblee.java
  week5/divide_and_conquer/색종이_만들기/Hyeblee.java
Labels: 분할 정복, !상급반

#74 상급반 / 박연준/ 색종이 만들기-2630, 222 풀링-17829, Z-1074, 별 찍기 10-2447
  week5/divide_and_conquer/222_풀링/QUWR.java
  week5/divide_and_conquer/Solution_QUWR.md
  week5/divide_and_conquer/Z/QUWR.java
  week5/divide_and_conquer/별_찍기_10/QUWR.java
  week5/divide_and_conquer/색종이_만들기/QUWR.java
Labels: 분할 정복, !상급반

#73 상급반 / 최수빈 / 색종이 만들기-2630, 222 풀링-17829, Z-1074, 별 찍기 10-2447
  week5/divide_and_conquer/222_풀링/subi930.java
  week5/divide_and_conquer/Solution_subi930.md
  week5/divide_and_conquer/Z/subi930.java
  week5/divide_and_conquer/별_찍기_10/subi930.java
  week5/divide_and_conquer/색종이_만들기/subi930.java
Labels: 분할 정복, !상급반

#72 상급반 / 정지태 / 색종이 만들기-2630, 222 풀링-17829, Z-1074, 별 찍기 10-2447
  week5/divide_and_conquer/222_폴링/JtJint.py
  week5/divide_and_conquer/Z/JtJint.py
  week5/divide_and_conquer/별_찍기/JtJint.py
  week5/divide_and_conquer/색종이_만들기/JtJint.py
Labels: 분할 정복, !상급반

#70 상급반 / 서상민 / 색종이 만들기-2630, 222 풀링-17829, Z-1074, 별 찍기 10-2447
  week5/divide_and_conquer/222_풀링/Solution_ss721229.md
  week5/divide_and_conquer/222_풀링/ss721229.py
  week5/divide_and_conquer/Z/Solution_ss721229.md
  week5/divide_and_conquer/Z/ss721229.py
  week5/divide_and_conquer/별_찍기_10/Solution_ss721229.md
  week5/divide_and_conquer/별_찍기_10/ss721229.py
  week5/divide_and_conquer/색종이_만들기/Solution_ss721229.md
  week5/divide_and_conquer/색종이_만들기/ss721229.py
Labels: 분할 정복, !상급반

#69 상급반 / 임효비 / 스택_수열-1874, 괄호의_값-2504, N번째_큰_수-2075, 문제_추천_시스템_Version_1-21939, 색종이_만들기-2630, 222_풀링-17829, Z-1074, 별_찍기_10-2447
  week1/datastructure/N번째_큰_수/Hyobi-Lim.py
  week1/datastructure/괄호의_값/Hyobi-Lim.py
  week1/datastructure/문제_추천_시스템_Version_1/Hyobi-Lim.py
  week1/datastructure/스택_수열/Hyobi-Lim.py
  week4/graph_traversal/숨바꼭질_3/Hyobi-Lim.py
  week4/graph_traversal/효율적인_해킹/Hyobi-Lim.py
  week5/divide_and_conquer/222_풀링/Hyobi-Lim.py
  week5/divide_and_conquer/222_풀링/Solution_[Hyobi-Lim].txt
  week5/divide_and_conquer/Z/Hyobi-Lim.py
  week5/divide_and_conquer/Z/Solution_[Hyobi-Lim].txt
  week5/divide_and_conquer/별_찍기_10/Hyobi-Lim.py
  week5/divide_and_conquer/별_찍기_10/Solution_[Hyobi-Lim].txt
  week5/divide_and_conquer/색종이_만들기/Hyobi-Lim.py
  week5/divide_and_conquer/색종이_만들기/Solution_[Hyobi-Lim].txt
Labels: 자료구조, 분할 정복, !상급반

#53 초급반/백승협/백트래킹_N과M_6-15655/완전탐색_블랙잭-2798,완전탐색_제곱수찾기-1025
  week3/backtracking/N과M_6/BaekSeungHyup/Main.java
  week3/brute_force/블랙잭/BaekSeungHyup/Main.java
  week3/brute_force/제곱수 찾기/BaekSeungHyup/Main.java
Labels: 완전탐색, 백트래킹, !초급반

#81 상급반 / 서상민 / 선수과목-14567, 음악프로그램-2623
  week6/topological_sorting/선수과목/ss721229.py
  week6/topological_sorting/음악프로그램/ss721229.py
Labels: 위상 정렬, !상급반

#82 상급반 / 정지태 / 선수과목-14567, 음악프로그램-2623
  week4/graph_traversal/움직이는_미로_탈출/JtJint.py
  week6/topological_sorting/선수과목/JtJint.py
  week6/topological_sorting/음악프로그램/JtJint.py
Labels: 위상 정렬, !상급반

#83 상급반 / 임효비 / 선수과목-14567, 음악프로그램-2623
  week6/topological_sorting/선수과목/Hyobi-Lim.py
  week6/topological_sorting/음악프로그램/Hyobi-Lim.py
Labels: 위상 정렬, !상급반

#84 상급반 / 박연준/ 선수과목-14567, 음악프로그램-2623
  week6/topological_sorting/선수과목/QUWR.java
  week6/topological_sorting/음악프로그램/QUWR.java
Labels: 위상 정렬, !상급반

#85 상급반 / 최수빈 / 선수과목-14567, 음악프로그램-2623
  week6/topological_sorting/선수과목/subi930.java
  week6/topological_sorting/음악프로그램/subi930.java
Labels: 위상 정렬, !상급반

#86 상급반 / 이혜빈 / 선수과목-14567, 음악프로그램-2623
  week6/topological_sorting/선수과목/Hyeblee.java
  week6/topological_sorting/음악프로그램/Hyeblee.java
Labels: 위상 정렬, !상급반

#87 상급반 / 장윤정 / 선수과목-14567, 음악프로그램-2623
  week6/topological_sorting/선수과목/Yooonjeong.java
  week6/topological_sorting/음악프로그램/Yooonjeong.java
Labels: 위상 정렬, !상급반

#88 상급반 / 김지훈 / 선수과목-14567, 음악프로그램-2623
  week6/topological_sorting/선수과목/applied7076.py
  week6/topological_sorting/음악_프로그램/applied7076.py
Labels: 위상 정렬, !상급반

#80 초급반 / 김현아 / DFS와 BFS-1260, 트리의 부모 찾기-11725, 숫자 고르기-2668, 색종이 만들기-2630, 쿼드트리-1992, 별찍기_11-2448
  week4/graph_traversal/DFS와_BFS/_10Hyuna/Main.java
  week4/graph_traversal/숫자고르기/_10Hyuna/Main.java
  week4/graph_traversal/트리의부모찾기/_10Hyuna/Main.java
  week5/divide_and_conquer/별찍기_11/_10Hyuna/Main.java
  week5/divide_and_conquer/색종이만들기/_10Hyuna/Main.java
  week5/divide_and_conquer/쿼드트리/_10Hyuna/Main.java
Labels: 그래프 탐색, 분할 정복, !초급반

#79 초급반 / 이승언 / DFS와 BFS-1260, 트리의 부모 찾기-11725, 숫자 고르기-2668, 색종이 만들기-2630, 쿼드트리-1992, 별찍기_11-2448
  week4/graph_traversal/DFS와_BFS/banasu0723/Main.java
  week4/graph_traversal/트리의부모찾기/banasu0723/Main.java
Labels: 그래프 탐색, 분할 정복, !초급반

#78 초급반 / 황재희 / DFS와 BFS-1260, 트리의 부모 찾기-11725, 숫자 고르기-2668, 색종이 만들기-2630, 쿼드트리-1992, 별찍기_11-2448
  week4/graph_traversal/DFS와_BFS/hwangjaehee.py
  week4/graph_traversal/숫자고르기/hwangjaehee.py
  week5/divide_and_conquer/별찍기_11/hwangjaehee.py
  week5/divide_and_conquer/색종이만들기/hwangjaehee.py
  week5/divide_and_conquer/쿼드트리/hwangjaehee.py
Labels: 그래프 탐색, 분할 정복, !초급반

#77 초급반 / 나의찬 / DFS와 BFS-1260, 트리의 부모 찾기-11725, 숫자 고르기-2668, 색종이 만들기-2630, 쿼드트리-1992, 별찍기_11-2448
  week4/graph_traversal/DFS와_BFS/Uechann/Main.java
  week4/graph_traversal/숫자고르기/Uechann/Main.java
  week4/graph_traversal/트리의부모찾기/Uechann/Main.java
  week5/divide_and_conquer/별찍기_11/Uechann/Main.java
  week5/divide_and_conquer/색종이만들기/Uechann/Main.java
  week5/divide_and_conquer/쿼드트리/Uechann/Main.java
Labels: 그래프 탐색, 분할 정복, !초급반

#58 초급반 / 김민지 / 돌게임 -9655, 합분해-2225, 선수과목-14567, 블랙잭-2798, 트리의 부모찾기-11725, 숫자 고르기-2668, DFS와 BFS-1260, 쿼드트리-1992, 색종이 만들기-2663
  week2/dynamic_programming/돌게임/arenran02/Main.cpp
  week2/dynamic_programming/선수과목/arenran02/Main.cpp
  week2/dynamic_programming/합분해/arenran02/Main.cpp
  week3/brute_force/블랙잭/arenran02/Main.cpp
  week4/graph_traversal/DFS와_BFS/arenran02/Main.cpp
  week4/graph_traversal/숫자고르기/arenran02/Main.cpp
  week4/graph_traversal/트리의부모찾기/arenran02/Main.cpp
  week5/divide_and_conquer/색종이만들기/arenran02/Main.cpp
  week5/divide_and_conquer/쿼드트리/arenran02/Main.cpp
Labels: 완전탐색, 백트래킹, 그래프 탐색, 분할 정복, !초급반

#99 상급반 / 김지훈 / 지뢰 찾기-4396, 빗물-14719, 완전이진트리-9934, 이진검색트리-5639
  week7/implementation/빗물/applied7076.py
  week7/implementation/지뢰_찾기/applied7076.py
  week8/tree/완전_이진_트리/applied7076.py
  week8/tree/이진_검색_트리/applied7076.py
Labels: 구현, !상급반
