Repository Alom-codingTest/alom-codingTest-25-1, pull requests merged in 2025-04, with the labels that each got.

#59 초급반 / 김현아 / 블랙잭 - 2798, N과M_6 - 15655, 제곱수찾기 - 1025
  week2/dynamic_programming/합분해/_10Hyuna/Main.java
  week3/backtracking/N과M_6/_10Hyuna/Main.java
  week3/brute_force/블랙잭/_10Hyuna/Main.java
  week3/brute_force/제곱수찾기/_10Hyuna/Main.java
Labels: 완전탐색, 백트래킹, !초급반

#55 초급반 / 나의찬 / N과M_6 - 15655, 블랙잭 - 2798, 제곱수찾기 - 1025
  week3/backtracking/N과M_6/Uechann/Main.java
  week3/brute_force/블랙잭/Uechann/Main.java
  week3/brute_force/제곱수찾기/Uechann/Main.java
Labels: 완전탐색, 백트래킹, !초급반

#38 초급반 / 황재희 / 돌게임 -9655, 합분해-2225, 선수과목-14567
  week2/dynamic_programming/돌게임/hwangjaehee.py
  week2/dynamic_programming/선수과목/hwangjaehee.py
  week2/dynamic_programming/합분해/hwangjaehee.py
  week3/backtracking/N과M_6/hwangjaehee.py
  week3/brute_force/블랙잭/hwangjaehee.py
  week3/brute_force/제곱수찾기/hwangjaehee.py
Labels: DP (동적 계획법), 완전탐색, 백트래킹, !초급반

#34 초급반 / 이승언 / 돌게임-9655, 합분해-2225, 선수과목-14567
  week2/dynamic_programming/돌게임/banasu0723/Main.java
  week2/dynamic_programming/선수과목/banasu0723/Main.java
  week2/dynamic_programming/합분해/banasu0723/Main.java
  week3/backtracking/N과M_6/banasu0723/Main.java
  week3/brute_force/블랙잭/banasu0723/Main.java
  week3/brute_force/제곱수찾기/banasu0723/Main.java
Labels: DP (동적 계획법), 완전탐색, 백트래킹, !초급반

#61 상급반 / 서상민 / 효율적인 해킹 - 1325, 숨바꼭질 3 - 13549, 숫자고르기 - 2668, 움직이는 미로 탈출 - 16954
  week4/graph_traversal/숨바꼭질_3/ss721229.py
  week4/graph_traversal/숫자고르기/ss721229.py
  week4/graph_traversal/움직이는_미로_탈출/ss721229.py
  week4/graph_traversal/효율적인_해킹/ss721229.py
Labels: 그래프 탐색, !상급반

#62 상급반 / 김지훈 / 효율적인 해킹 - 1325, 숨바꼭질 3 - 13549, 숫자고르기 - 2668, 움직이는 미로 탈출 - 16954
  week4/graph_traversal/숨바꼭질_3/applied7076.py
  week4/graph_traversal/숫자고르기/applied7076.py
  week4/graph_traversal/움직이는_미로_탈출/applied7076.py
  week4/graph_traversal/효율적인_해킹/applied7076.cpp
  week4/graph_traversal/효율적인_해킹/applied7076.py
Labels: 그래프 탐색, !상급반

#63 상급반 / 이혜빈 / 효율적인 해킹 - 1325, 숨바꼭질 3 - 13549, 숫자고르기 - 2668, 움직이는 미로 탈출 - 16954
  week4/graph_traversal/숨바꼭질_3/Hyeblee.java
  week4/graph_traversal/숫자고르기/Hyeblee.java
  week4/graph_traversal/움직이는_미로_탈출/Hyeblee.java
  week4/graph_traversal/효율적인_해킹/Hyeblee.java
Labels: 그래프 탐색, !상급반

#65 상급반 / 박연준/ 숨바꼭질3-13549, 효율적인_해킹-1325, 숫자고르기-2668, 움직이는_미로_탈출-16954
  week4/graph_traversal/숨바꼭질_3/QUWR.java
  week4/graph_traversal/숫자고르기/QUWR.java
  week4/graph_traversal/움직이는_미로_탈출/QUWR.java
  week4/graph_traversal/효율적인_해킹/QUWR.java
Labels: 그래프 탐색, !상급반

#64 상급반 / 정지태 / 숨바꼭질_3-13549, 효율적인_해킹-1325, 숫자고르기-2668, 움직이는_미로_탈출-16954
  week4/graph_traversal/숨바꼭질_3/JtJint.py
  week4/graph_traversal/숫자고르기/JtJint.py
  week4/graph_traversal/움직이는_미로_탈출/JtJint.py
  week4/graph_traversal/효율적인_해킹/JtJint.py
Labels: 그래프 탐색, !상급반

#66 상급반 / 장윤정 / 효율적인 해킹 - 1325, 숨바꼭질 3 - 13549, 숫자고르기 - 2668, 움직이는 미로 탈출 - 16954
  week4/graph_traversal/숨바꼭질_3/Yooonjeong.java
  week4/graph_traversal/숫자고르기/Yooonjeong.java
  week4/graph_traversal/움직이는_미로_탈출/Yooonjeong.java
  week4/graph_traversal/효율적인_해킹/Yooonjeong.java
Labels: 그래프 탐색, !상급반

#67 상급반 / 임효비 / 효율적인 해킹-1325, 숨바꼭질 3-13549, 숫자고르기-2668, 움직이는 미로 탈출-16954
  week4/graph_traversal/숨바꼭질_3/Hyobi-Lim.py
  week4/graph_traversal/숫자고르기/Hyobi-Lim.py
  week4/graph_traversal/움직이는_미로_탈출/Hyobi-Lim.py
  week4/graph_traversal/효율적인_해킹/Hyobi-Lim.py
Labels: 그래프 탐색, !상급반

#68 상급반 / 최수빈 / 효율적인_해킹-1325, 숨바꼭질_3-13549, 숫자고르기-2668, 움직이는_미로_탈출-16954
  week4/graph_traversal/숨바꼭질_3/subi930.java
  week4/graph_traversal/숫자고르기/subi930.java
  week4/graph_traversal/움직이는_미로_탈출/subi930.java
  week4/graph_traversal/효율적인_해킹/subi930.java
Labels: 그래프 탐색, !상급반
