Repository Alom-codingTest/alom-codingTest-25-1, pull requests merged in 2025-03, with the labels that each got.

#4 고급반 / 서상민 / 스택_수열-1874, 괄호의_값-2504, N번째_큰_수-2075, 문제_추천_시스템_Version_1-21939
  week1/datastructure/N번째_큰_수/ss721229.py
  week1/datastructure/괄호의_값/ss721229.py
  week1/datastructure/문제_추천_시스템_Version_1/ss721229.py
  week1/datastructure/스택_수열/ss721229.py
Labels: 자료구조

#5 고급반 / 김지훈 / 스택_수열-1874, 괄호의_값-2504, N번째_큰_수-2075, 문제_추천_시스템_Version_1-21939
  week1/datastructure/N번째_큰_수/applied7076.py
  week1/datastructure/괄호의_값/applied7076.py
  week1/datastructure/문제_추천_시스템_Version_1/applied7076.py
  week1/datastructure/스택_수열/applied7076.py
Labels: 자료구조

#14 상급반 / 장윤정 / 스택 수열-1874, 괄호의 값-2504, N번째 큰 수-2075, 문제 추천 시스템 Version 1-21939
  week1/datastructure/N번째_큰_수/Yooonjeong.java
  week1/datastructure/괄호의_값/Yooonjeong.java
  week1/datastructure/문제_추천_시스템_Version_1/Yooonjeong.java
  week1/datastructure/스택_수열/Yooonjeong.java
Labels: 자료구조, !상급반

#3 초급반 / 김현아 / 큐2-18258, 스택-10828, 최대힙-11279
  week1/datastructure/스택/_10Hyuna/Main.java
  week1/datastructure/최대힙/_10Hyuna/Main.java
  week1/datastructure/큐2/_10Hyuna/Main.java
Labels: 자료구조, !초급반

#7 초급반 / 나의찬 / 큐2-18258, 스택-10828, 최대힙-11279
  week1/datastructure/스택/Uechann/Main.java
  week1/datastructure/최대힙/Uechann/Main.java
  week1/datastructure/큐2/Uechann/Main.java
Labels: 자료구조, !초급반

#8 초급반 / 이승언 / 큐2-18258, 스택-10828, 최대힙-11279
  week1/datastructure/스택/banasu0723/Main.java
  week1/datastructure/최대힙/banasu0723/Main.java
  week1/datastructure/큐2/banasu0723/Main.java
Labels: 자료구조, !초급반

#12 초급반 / 김세현 / 큐2-18258, 최대 힙-11279, 스택-10828
  week1/datastructure/스택/sehxxnee/stack.py
  week1/datastructure/최대힙/sehxxnee/heap.py
  week1/datastructure/큐2/sehxxnee/que.py
Labels: 자료구조, !초급반

#6 초급반 / 황재희 / 큐2-18258, 스택-10828, 최대힙-11279
  week1/datastructure/스택/hwangjaehee.py
  week1/datastructure/최대힙/hwangjaehee.py
  week1/datastructure/큐2/hwangjaehee.py
Labels: 자료구조, !초급반

#10 초급반 / 백승협 / 큐2-18258, 스택-10828, 최대힙-11279
  week1/datastructure/스택.BaekSeungHyup/Main.java
  week1/datastructure/최대힙.BaekSeungHyup/Main.java
  week1/datastructure/큐2.BaekSeungHyup/Main.java
Labels: 자료구조, !초급반

#13 초급반 / 김민지 / 큐2-18258, 최대 힙-11279, 스택-10828
  week1/datastructure/스택/arenran02/Main.cpp
  week1/datastructure/최대 힙/arenran02/Main.cpp
  week1/datastructure/큐2/arenran02/Main.cpp
Labels: 자료구조, !초급반

#19 상급반 / 장윤정 / 1로 만들기-1463, 가장 긴 증가하는 부분 수열-11053, 동전-9084, 양팔저울-2629
  week2/dynamic_programming/1로 만들기/Yooonjeong.java
  week2/dynamic_programming/가장 긴 증가하는 부분 수열/Yooonjeong.java
  week2/dynamic_programming/동전/Yooonjeong.java
  week2/dynamic_programming/양팔저울/Yooonjeong.java
Labels: DP (동적 계획법), !상급반

#20 상급반 / 서상민 / 1로 만들기-1463, 가장 긴 증가하는 부분 수열-11053, 동전-9084, 양팔저울-2629
  week2/dynamic_programming/1로_만들기/ss721229.py
  week2/dynamic_programming/가장_긴_증가하는_부분_수열/ss721229.py
  week2/dynamic_programming/동전/ss721229.py
  week2/dynamic_programming/양팔저울/ss721229.py
Labels: DP (동적 계획법), !상급반

#21 상급반 / 김지훈 / 1로 만들기-1463, 가장 긴 증가하는 부분 수열-11053, 동전-9084, 양팔저울-2629
  week2/dynamic_programming/1로_만들기/applied7076.py
  week2/dynamic_programming/가장_긴_증가하는_부분_수열/applied7076.py
  week2/dynamic_programming/동전/applied7076.py
  week2/dynamic_programming/양팔저울/applied7076.py
Labels: DP (동적 계획법), !상급반

#23 상급반 / 최수빈 /스택수열-1874, N번째_큰수-2075, 괄호의값-2504, 문체추천시스템V1-21939, 1로 만들기-1463, 가장 긴 증가하는 부분 수열-11053, 동전-9084, 양팔저울-2629
  week1/datastructure/N번째_큰_수/subi930.java
  week1/datastructure/괄호의_값/subi930.java
  week1/datastructure/문제_추천_시스템_Version_1/subi930.java
  week1/datastructure/스택_수열/subi930.java
  week2/dynamic_programming/1로_만들기/subi930.java
  week2/dynamic_programming/가장_긴_증가하는_부분_수열/subi930.java
  week2/dynamic_programming/동전/subi930.java
  week2/dynamic_programming/양팔저울/subi930.java
Labels: 자료구조, DP (동적 계획법), !상급반

#28 상급반 / 이혜빈 / 스택수열-1874, N번째_큰수-2075, 괄호의값-2504, 문체추천시스템V1-21939, 1로 만들기-1463
  week1/datastructure/N번째_큰_수/Hyeblee.java
  week1/datastructure/괄호의_값/Hyeblee.java
  week1/datastructure/문제_추천_시스템_Version_1/Hyeblee.java
  week1/datastructure/스택_수열/Hyeblee.java
  week2/dynamic_programming/1로_만들기/Hyeblee.java
  week2/dynamic_programming/가장_긴_증가하는_부분_수열/Hyeblee.java
  week2/dynamic_programming/동전/Hyeblee.java
Labels: 자료구조, DP (동적 계획법), !상급반

#26 초급반/ 백승협/ 돌게임-9655, 합분해-2225, 선수과목 -14567
  week2/dynamic_programming/돌게임.BaekSeungHyup/main.java
  week2/dynamic_programming/선수과목/BaekSeungHyup/main.java
  week2/dynamic_programming/합분해.BaekSeungHyup/main.java
Labels: DP (동적 계획법), !초급반

#30 초급반 / 김현아 / 돌게임-9655, 합분해-2225, 선수과목-14567
  week2/dynamic_programming/돌게임/_10Hyuna/Main.java
  week2/dynamic_programming/선수과목/_10Hyuna/Main.java
  week2/dynamic_programming/합분해/_10Hyuna/Main.java
Labels: DP (동적 계획법), !초급반

#31 초급반 / 나의찬 / 돌게임-9655, 합분해-2225, 선수과목-14567
  week2/dynamic_programming/돌게임/Uechann/Main.java
  week2/dynamic_programming/선수과목/Uechann/Main.java
  week2/dynamic_programming/합분해/Uechann/Main.java
Labels: DP (동적 계획법), !초급반

#39 상급반 / 김지훈 / N과 M 2 - 15650, 스도쿠 - 2580, 동전 게임 - 9079, A와 B 2 - 12919
  week3/backtracking/N과_M_2/applied7076.py
  week3/backtracking/스도쿠/applied7076.py
  week3/brute_force/A와_B_2/applied7076.py
  week3/brute_force/동전_게임/applied7076.py
Labels: 완전탐색, 백트래킹, 그래프 탐색, !상급반

#40 상급반 / 장윤정 / N과 M 2 - 15650, 스도쿠 - 2580, 동전 게임 - 9079, A와 B 2 - 12919
  week3/backtracking/N과_M_2/Yooonjeong.java
  week3/backtracking/스도쿠/Yooonjeong.java
  week3/brute_force/A와_B_2/Yooonjeong.java
  week3/brute_force/동전_게임/Yooonjeong.java
Labels: 완전탐색, 백트래킹, 그래프 탐색, !상급반

#41 상급반 / 이혜빈 / 양팔저울 - 2629 , N과 M 2 - 15650, 스도쿠 - 2580, 동전 게임 - 9079, A와 B 2 - 12919
  week2/dynamic_programming/양팔저울/Hyeblee.java
  week3/backtracking/N과_M_2/Hyeblee.java
  week3/backtracking/스도쿠/Hyeblee.java
  week3/brute_force/A와_B_2/Hyeblee.java
  week3/brute_force/동전_게임/Hyeblee.java
Labels: 완전탐색, 백트래킹, 그래프 탐색, !상급반

#42 상급반 / 서상민 / N과 M 2 - 15650, 스도쿠 - 2580, 동전 게임 - 9079, A와 B 2 - 12919
  week3/backtracking/N과_M_2/ss721229.py
  week3/backtracking/스도쿠/ss721229.py
  week3/brute_force/A와_B_2/ss721229.py
  week3/brute_force/동전_게임/ss721229.py
Labels: 완전탐색, 백트래킹, 그래프 탐색, !상급반

#43 상급반 / 박연준/ N과 M 2 - 15650, 스도쿠 - 2580, 동전 게임 - 9079, A와 B 2 - 12919
  week3/backtracking/N과_M_2/QUWR.java
  week3/backtracking/스도쿠/QUWR.java
  week3/brute_force/A와_B_2/QUWR.java
  week3/brute_force/동전_게임/QUWR.java
Labels: 완전탐색, 백트래킹, 그래프 탐색, !상급반

#48 상급반 / 최수빈 / N과 M 2 - 15650, 스도쿠 - 2580, 동전 게임 - 9079, A와 B 2 - 12919
  week3/backtracking/N과_M_2/subi930.java
  week3/backtracking/스도쿠/subi930.java
  week3/brute_force/A와_B_2/subi930.java
  week3/brute_force/동전_게임/subi930.java
Labels: 완전탐색, 백트래킹, 그래프 탐색, !상급반

#57 상급반 / 정지태 / ~3주차
  week1/datastructure/N번째_큰_수/JtJint.py
  week1/datastructure/괄호의_값/JtJint.py
  week1/datastructure/문제_추천_시스템_Version_1/JtJint.py
  week1/datastructure/스택_수열/JtJint.py
  week2/dynamic_programming/1로_만들기/JtJint.py
  week2/dynamic_programming/가장_긴_증가하는_부분_수열/JtJint.py
  week2/dynamic_programming/동전/JtJint.py
  week2/dynamic_programming/양팔저울/JtJint.py
  week3/backtracking/N과_M_2/JtJint.py
  week3/backtracking/스도쿠/JtJint.py
  week3/brute_force/A와_B_2/JtJint.py
  week3/brute_force/동전_게임/JtJint.py
Labels: !상급반
